# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Fetch tags
      run: git fetch --prune --unshallow --tags

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2.0.0
      with:
        nuget-api-key: ${NUGET}          
  
    - name: Install Maui Workload
      run: dotnet workload install maui --ignore-failed-sources
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: msbuild SparkIO.sln -property:Configuration=Release

    - name: Publish Nuget
      run: |
        nuget push '**/*.nupkg' -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
      env:
        NUGET: ${{ secrets.NUGET }}
